# -*- coding: utf-8 -*-
"""Yolo26_Bintang.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLIiJitgICtVoRndrvO65pto_7N-G3Ra
"""

# Blok 1: Menyambungkan ke Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Blok 2: Instalasi pustaka
!pip install ultralytics roboflow

# 1. Bersihkan sisa dataset lama yang mungkin masih tertinggal
!rm -rf train valid test data.yaml roboflow.zip

# 2. Unduh dataset Versi 2 yang baru saja kamu buat
!curl -L "https://app.roboflow.com/ds/T6j66ws5Qp?key=RUNmKstpZf" > roboflow.zip

# 3. Ekstrak file zip secara diam-diam (-q) agar layar tidak penuh teks
!unzip -q roboflow.zip

# 4. Hapus file zip yang sudah tidak terpakai untuk menghemat memori
!rm roboflow.zip

# !yolo task=segment mode=train model=yolo26n-seg.pt data=/content/data.yaml epochs=100 imgsz=640 name=Run_2_Pothole_Campuran project=/content/drive/MyDrive/Penelitian_YOLO26

# !yolo task=segment mode=track model=/content/drive/MyDrive/Penelitian_YOLO26/Run_2_Pothole_Campuran/weights/best.pt source=/content/p.mp4 save=True name=Hasil_Uji_Coba_2

from google.colab import files
import glob
import os

# Mencari video hasil prediksi di dalam folder Hasil_Uji_Coba_2
semua_video = glob.glob('runs/segment/Hasil_Uji_Coba_2/*.avi') + glob.glob('runs/segment/Hasil_Uji_Coba_2/*.mp4')

if semua_video:
    # Mengambil file video terbaru
    video_terbaru = max(semua_video, key=os.path.getmtime)
    print(f"🎬 Menyiapkan unduhan untuk: {video_terbaru}")
    files.download(video_terbaru)
else:
    print("❌ Video hasil belum ditemukan. Pastikan Langkah 1 sudah selesai 100%.")

import cv2
from ultralytics import YOLO
import numpy as np
import os
from google.colab import files

# ==========================================
# KONFIGURASI WARNA YOLOV8 (KUSTOM)
# ==========================================
WARNA_HIJAU = (0, 200, 0)     # Hijau sehat (BGR) untuk Box, Label, dan Poligon
WARNA_TEKS = (255, 255, 255)  # Putih (seperti bawaan YOLO)
KETEBALAN_GARIS = 2
UKURAN_FONT = 0.5             # Ukuran standar YOLO
KETEBALAN_FONT = 1
# ==========================================

# 1. Muat Model AI Kamu (Run_2)
model_path = '/content/drive/MyDrive/Penelitian_YOLO26/Run_2_Pothole_Campuran/weights/best.pt'
model = YOLO(model_path)

# 2. Buka Video Sumber
video_path = '/content/p.mp4'
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    print("❌ Error: Gagal membuka video.")
    exit()

# Dapatkan properti video
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
fps = cap.get(cv2.CAP_PROP_FPS)

# 3. Siapkan Video Writer
output_path = '/content/sample_video_HIJAU_YOLO.mp4'
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))

print("🎬 Memproses video dengan gaya YOLO Hijau (Tanpa Masker)...")

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Jalankan Tracking
    results = model.track(frame, persist=True, verbose=False, conf=0.3)

    if results[0].boxes.id is not None and results[0].masks is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        ids = results[0].boxes.id.cpu().numpy().astype(int)
        confs = results[0].boxes.conf.cpu().numpy()
        clss = results[0].boxes.cls.cpu().numpy().astype(int)
        masks = results[0].masks.xy

        class_names = model.names

        for box, id_num, conf, cls_idx, mask_polygons in zip(boxes, ids, confs, clss, masks):
            x1, y1, x2, y2 = map(int, box)

            # --- A. GAMBAR BOUNDING BOX HIJAU ---
            cv2.rectangle(frame, (x1, y1), (x2, y2), WARNA_HIJAU, KETEBALAN_GARIS)

            # --- B. GAMBAR GARIS POLIGON HIJAU (TANPA MASKER ISI) ---
            if len(mask_polygons) > 0:
                polygon_coords = mask_polygons.astype(np.int32)
                cv2.polylines(frame, [polygon_coords], True, WARNA_HIJAU, KETEBALAN_GARIS)

            # --- C. RACIK TEKS SEPERTI BAWAAN YOLO ---
            # Format persis seperti gambar biru: "id:XX severity-1 0.XX"
            label = f"id:{id_num} {class_names[cls_idx]} {conf:.2f}"

            # --- D. BUAT KOTAK BACKGROUND LABEL ---
            # Hitung ukuran teks untuk membuat kotak latar belakang yang pas
            (w, h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, KETEBALAN_FONT)

            # Gambar kotak filled (-1) sebagai background teks
            cv2.rectangle(frame, (x1, y1 - h - 8), (x1 + w + 2, y1), WARNA_HIJAU, -1)

            # --- E. TULIS TEKS PUTIH DI ATAS KOTAK HIJAU ---
            cv2.putText(frame, label, (x1 + 1, y1 - 4),
                        cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, WARNA_TEKS,
                        KETEBALAN_FONT, cv2.LINE_AA)

    # Simpan frame
    out.write(frame)

cap.release()
out.release()
print("✅ Pemrosesan selesai!")

# ==========================================
# PROSES UNDUHAN OTOMATIS
# ==========================================
if os.path.exists(output_path):
    print(f"📥 Menyiapkan unduhan untuk: {output_path}")
    files.download(output_path)
else:
    print("❌ Video hasil belum ditemukan.")

import cv2
from ultralytics import YOLO
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files
import os

# ==========================================
# KONFIGURASI ESTETIKA IDENTIK YOLO (HIJAU)
# ==========================================
# Warna "Hijau Sehat" bawaan pabrik (BGR)
WARNA_HIJAU_YOLO = (56, 219, 96) # Hijau terang khas Ultralytics tapi sehat
WARNA_TEKS_PUTIH = (255, 255, 255)
KETEBALAN_GARIS = 2
UKURAN_FONT = 0.5            # Standar minimalis YOLO
KETEBALAN_FONT = 1
# TRANSPARANSI MASKER (Agar lubang tetap terlihat sedikit)
# Gunakan 0.3 untuk tipis, 0.5 untuk sedang (seperti videomu dulu)
TINGKAT_TRANSPARANSI = 0.4
# ==========================================

# 1. Muat Model AI YOLO26 Kamu
model_path = '/content/drive/MyDrive/Penelitian_YOLO26/Run_2_Pothole_Campuran/weights/best.pt'
if not os.path.exists(model_path):
    print(f"❌ Error: Model tidak ditemukan di Drive! Pastikan path benar: {model_path}")
    exit()

model = YOLO(model_path)

# 2. Siapkan Gambar Sumber
# Silakan upload foto lubang dan ubah nama jadi 'pothole_test.jpg' di folder content
image_path = '/content/pothole_test.jpg'
img = cv2.imread(image_path)

if img is None:
    print("❌ Error: Gambar 'pothole_test.jpg' tidak ditemukan di folder content! Silakan upload dulu.")
else:
    print("🎬 Memproses gambar dengan gaya visual IDENTIK YOLO Hijau...")

    # Siapkan overlay untuk masker transparan
    img_final = img.copy()
    mask_overlay = np.zeros_like(img, dtype=np.uint8)

    # 3. Jalankan Prediksi (Menggunakan mode .predict untuk gambar statis)
    # verbose=False agar layar tidak penuh teks
    results = model.predict(img, verbose=False, conf=0.3)

    # Pastikan ada objek segmen poligon yang terdeteksi
    if results[0].boxes is not None and results[0].masks is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        confs = results[0].boxes.conf.cpu().numpy()
        clss = results[0].boxes.cls.cpu().numpy().astype(int)
        masks = results[0].masks.xy # Koordinat poligon

        class_names = model.names

        # Iterasi setiap objek lubang di dalam foto
        for box, conf, cls_idx, mask_polygons in zip(boxes, confs, clss, masks):
            x1, y1, x2, y2 = map(int, box)

            # --- A. GAMBAR BOUNDING BOX HIJAU TEBAL ---
            cv2.rectangle(img_final, (x1, y1), (x2, y2), WARNA_HIJAU_YOLO, KETEBALAN_GARIS)

            # --- B. GAMBAR ISIAN MASKER SEMI-TRANSPARAN (FILLED MASK) ---
            if len(mask_polygons) > 0:
                polygon_coords = mask_polygons.astype(np.int32)
                # Gambar poligon hijau penuh di mask_overlay
                cv2.fillPoly(mask_overlay, [polygon_coords], WARNA_HIJAU_YOLO)
                # Gambar garis tepi poligon agar tajam (seperti videomu dulu)
                cv2.polylines(img_final, [polygon_coords], True, WARNA_HIJAU_YOLO, KETEBALAN_GARIS)

            # --- C. RACIK TEKS SEPERTI BAWAAN YOLO (KELAS + CONF) ---
            orig_cls_name = class_names[cls_idx]
            label = f"{orig_cls_name} {conf:.2f}" # Contoh: severity-1 0.55

            # --- D. BUAT KOTAK BACKGROUND LABEL HIJAU TEBAL ---
            # Hitung ukuran teks
            (w, h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, KETEBALAN_FONT)

            # Tentukan posisi kotak label (di atas kotak deteksi)
            # Pastikan tidak keluar layar atas
            label_y = y1
            if label_y < h + 10: label_y = h + 10

            # Gambar kotak latar belakang hijau penuh (-1)
            cv2.rectangle(img_final, (x1, label_y - h - 8), (x1 + w + 4, label_y), WARNA_HIJAU_YOLO, -1)

            # --- E. TULIS TEKS PUTIH DI ATAS KOTAK HIJAU ---
            cv2.putText(img_final, label, (x1 + 2, label_y - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, WARNA_TEKS_PUTIH,
                        KETEBALAN_FONT, cv2.LINE_AA)

    # 4. Gabungkan Masker Transparan dengan Gambar Utama
    # Ini yang membuat isian warna hijau jadi tembus pandang
    cv2.addWeighted(mask_overlay, TINGKAT_TRANSPARANSI, img_final, 1, 0, img_final)

    # 5. Tampilkan Hasil Langsung di Colab
    print("\n📸 HASIL DETEKSI AI (GAYA KUSTOM IDENTIK YOLO HIJAU):")
    cv2_imshow(img_final)

    # 6. Simpan Gambar Hasil
    output_path = '/content/hasil_deteksi_gambar_HIJAU.jpg'
    cv2.imwrite(output_path, img_final)
    print(f"\n✅ Gambar hasil disimpan di: {output_path}")

    # 7. Unduh Otomatis
    print("📥 Menyiapkan unduhan otomatis...")
    files.download(output_path)

import cv2
from ultralytics import YOLO
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files
import os

# ==========================================
# KONFIGURASI ESTETIKA IDENTIK YOLO (HIJAU)
# ==========================================
# Warna "Hijau Sehat" bawaan pabrik (BGR)
WARNA_HIJAU_YOLO = (56, 219, 96) # Hijau terang khas Ultralytics tapi sehat
WARNA_TEKS_PUTIH = (255, 255, 255)
KETEBALAN_GARIS = 2
UKURAN_FONT = 0.5            # Standar minimalis YOLO
KETEBALAN_FONT = 1
# TRANSPARANSI MASKER (Agar lubang tetap terlihat sedikit)
# Gunakan 0.3 untuk tipis, 0.5 untuk sedang (seperti videomu dulu)
TINGKAT_TRANSPARANSI = 0.4
# ==========================================

# 1. Muat Model AI YOLO26 Kamu
model_path = '/content/drive/MyDrive/Penelitian_YOLO26/Run_2_Pothole_Campuran/weights/best.pt'
if not os.path.exists(model_path):
    print(f"❌ Error: Model tidak ditemukan di Drive! Pastikan path benar: {model_path}")
    exit()

model = YOLO(model_path)

# 2. Siapkan Gambar Sumber
# Silakan upload foto lubang dan ubah nama jadi 'pothole_test.jpg' di folder content
image_path = '/content/pothole_test.jpg'
img = cv2.imread(image_path)

if img is None:
    print("❌ Error: Gambar 'pothole_test.jpg' tidak ditemukan di folder content! Silakan upload dulu.")
else:
    print("🎬 Memproses gambar dengan gaya visual IDENTIK YOLO Hijau...")

    # Siapkan overlay untuk masker transparan
    img_final = img.copy()
    mask_overlay = np.zeros_like(img, dtype=np.uint8)

    # 3. Jalankan Prediksi (Menggunakan mode .predict untuk gambar statis)
    # verbose=False agar layar tidak penuh teks
    results = model.predict(img, verbose=False, conf=0.3)

    # Pastikan ada objek segmen poligon yang terdeteksi
    if results[0].boxes is not None and results[0].masks is not None:
        boxes = results[0].boxes.xyxy.cpu().numpy()
        confs = results[0].boxes.conf.cpu().numpy()
        clss = results[0].boxes.cls.cpu().numpy().astype(int)
        masks = results[0].masks.xy # Koordinat poligon

        class_names = model.names

        # Iterasi setiap objek lubang di dalam foto
        for box, conf, cls_idx, mask_polygons in zip(boxes, confs, clss, masks):
            x1, y1, x2, y2 = map(int, box)

            # --- A. GAMBAR BOUNDING BOX HIJAU TEBAL ---
            cv2.rectangle(img_final, (x1, y1), (x2, y2), WARNA_HIJAU_YOLO, KETEBALAN_GARIS)

            # --- B. GAMBAR ISIAN MASKER SEMI-TRANSPARAN (FILLED MASK) ---
            if len(mask_polygons) > 0:
                polygon_coords = mask_polygons.astype(np.int32)
                # Gambar poligon hijau penuh di mask_overlay
                cv2.fillPoly(mask_overlay, [polygon_coords], WARNA_HIJAU_YOLO)
                # Gambar garis tepi poligon agar tajam (seperti videomu dulu)
                cv2.polylines(img_final, [polygon_coords], True, WARNA_HIJAU_YOLO, KETEBALAN_GARIS)

            # --- C. RACIK TEKS SEPERTI BAWAAN YOLO (KELAS + CONF) ---
            orig_cls_name = class_names[cls_idx]
            label = f"{orig_cls_name} {conf:.2f}" # Contoh: severity-1 0.55

            # --- D. BUAT KOTAK BACKGROUND LABEL HIJAU TEBAL ---
            # Hitung ukuran teks
            (w, h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, KETEBALAN_FONT)

            # Tentukan posisi kotak label (di atas kotak deteksi)
            # Pastikan tidak keluar layar atas
            label_y = y1
            if label_y < h + 10: label_y = h + 10

            # Gambar kotak latar belakang hijau penuh (-1)
            cv2.rectangle(img_final, (x1, label_y - h - 8), (x1 + w + 4, label_y), WARNA_HIJAU_YOLO, -1)

            # --- E. TULIS TEKS PUTIH DI ATAS KOTAK HIJAU ---
            cv2.putText(img_final, label, (x1 + 2, label_y - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, UKURAN_FONT, WARNA_TEKS_PUTIH,
                        KETEBALAN_FONT, cv2.LINE_AA)

    # 4. Gabungkan Masker Transparan dengan Gambar Utama
    # Ini yang membuat isian warna hijau jadi tembus pandang
    cv2.addWeighted(mask_overlay, TINGKAT_TRANSPARANSI, img_final, 1, 0, img_final)

    # 5. Tampilkan Hasil Langsung di Colab
    print("\n📸 HASIL DETEKSI AI (GAYA KUSTOM IDENTIK YOLO HIJAU):")
    cv2_imshow(img_final)

    # 6. Simpan Gambar Hasil
    output_path = '/content/hasil_deteksi_gambar_HIJAU.jpg'
    cv2.imwrite(output_path, img_final)
    print(f"\n✅ Gambar hasil disimpan di: {output_path}")

    # 7. Unduh Otomatis
    print("📥 Menyiapkan unduhan otomatis...")
    files.download(output_path)

!yolo task=segment mode=predict model=/content/drive/MyDrive/Penelitian_YOLO26/Run_2_Pothole_Campuran/weights/best.pt source=/content/drive/MyDrive/Penelitian_YOLO26/p.mp4 save=True project=/content/drive/MyDrive/Penelitian_YOLO26 name=Hasil_Prediksi

from IPython.display import HTML
from base64 import b64encode

# Masukkan lokasi path video HASIL PREDIKSI yang sudah jadi di sini
video_path = '/content/drive/MyDrive/Penelitian_YOLO26/Hasil_Prediksi/p.avi'

mp4 = open(video_path, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=600 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)